version: '3.8'

services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    environment:
      POSTGRES_DB: RestAPI_test_generator_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  backend:
    image: azizsnoussi/rest-api-test-generator
    container_name: backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/RestAPI_test_generator_DB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"
    networks:
      - app-network
    volumes:
      - ./public:/public

  frontend:
    image: azizsnoussi/rtg-ng-frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
volumes:
  postgresql_data:
  prometheus_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
